version: 2.1

jobs:
  setup:
    docker:
      - image: cimg/node:19.5.0
    resource_class: large
    parallelism: 10

    steps:
      - checkout

      - restore_cache:
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}

      - run:
          name: 'Install dependencies'
          command: pnpm install

      - save_cache:
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: .
          paths:
            - ./*

  build:
    docker:
      - image: cimg/node:19.5.0

    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: 'Build packages'
          command: pnpm compile
      - persist_to_workspace:
          root: .
          paths:
            - ./src

  lint:
    docker:
      - image: cimg/node:19.5.0

    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: 'Verify code quality and formatting'
          command: pnpm lint

  test:
    docker:
      - image: cimg/node:19.5.0

    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: 'Run unit tests'
          command: pnpm test

  typecheck:
    docker:
      - image: cimg/node:19.5.0

    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: 'Run typechecks'
          command: pnpm typecheck

  prettier:
    docker:
      - image: cimg/node:19.5.0

    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: 'Run prettier'
          command: pnpm prettier --check .

workflows:
  test-and-build:
    jobs:
      - setup:
          context: readonly-github-packages

      - build:
          requires:
            - setup

      - lint:
          requires:
            - build

      - test:
          requires:
            - build

      - typecheck:
          requires:
            - build

      - prettier:
          requires:
            - build
